version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sel"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t6qkoxji07g8"
s3_prefix = "sel"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["SeleniumFunction=291980285112.dkr.ecr.us-west-1.amazonaws.com/sel8be74552/seleniumfunction930ef00frepo"]
