name: Deploy Docker image for webscraping lambda

on:
  push:
    branches: [ main ]
    
jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
    - working-directory: deployment/lambda_webscraper
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REPO_URI }}
        ECR_REPOSITORY: lambdas
        IMAGE_TAG: webscraper_latest
      run: |
        docker build -t Dockerfile $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
